export type Job = {
  id: string;
  title: string;
  company: string;
  location: string;
  description: string;
  score: number;
  reason: string;
  status: 'Discovery' | 'Triage' | 'Drafting' | 'Ready' | 'Applied' | 'Recruiter Screen' | 'Technical Round' | 'Portfolio Presentation' | '2nd Interview' | 'Final Round' | 'Offer' | 'Rejected' | 'Cancelled';
  url: string;
  source: string;
  createdAt: string;
  matchedRole?: string;
  // Enrichment fields
  isFavourite?: boolean;
  salaryRange?: string;           // e.g. "$70,000 – $90,000" or null if not listed
  aiSalaryEstimate?: string;      // AI-estimated salary range, e.g. "$55,000 – $70,000"
  aiSalaryBasis?: string;         // Brief source note e.g. "Based on BLS data for FL logistics roles"
  postedAt?: string;              // ISO date string from listing, if available
  ghostScore?: number;            // 0–100, higher = more likely a ghost/recurring post
  applicationStatus?: ApplicationStatus;
  tailoredResumeText?: string;    // AI-rewritten resume for this specific job
  coverLetterText?: string;       // AI cover letter for this specific job
  recruiterHookLinkedin?: string; // AI-generated LinkedIn hook
  recruiterHookEmail?: string;    // AI-generated Email follow-up
  applicationNotes?: string;      // User notes / recruiter contact
  submittedAt?: string;           // When the application was submitted
  formFieldAnswers?: Record<string, string>; // Saved answers for unusual form fields
  referralRoutes?: ReferralRoute[];
  interviewPrepData?: {
    pitch?: string;
    behavioralQuestions?: Array<{ q: string; a: string }>;
    technicalQuestions?: Array<{ q: string; a: string }>;
    reverseQuestions?: string[];
    salaryNegotiation?: string;
  };
  
  // Exact Database Columns from Catalog specifications
  job_id?: string;                // Reference to the scraped job listing (UUID)
  salary_range?: string;          // Advertised salary range
  resume_version_used?: string;   // Name/hash of the custom resume submitted
  tailored_highlights?: string;   // Custom bullet points/summary generated by AI
  salary_expectations?: {
    minimumAcceptable: number;
    targetSalary: number;
    maximumAsk: number;
    negotiable: boolean;
    currency: 'GBP' | 'USD' | 'EUR';
  };
  recruiter_details?: {
    name?: string;
    email?: string;
    linkedinUrl?: string;
    notes?: string;
  };
  screening_answers?: Record<string, string>;
  receipt_screenshot?: string;
  submitted_at?: string;
  last_updated?: string;
  notes?: string;
};

export type ReferralRoute = {
  name: string;
  role: string;
  connectionType: 'Alumni' | 'Ex-Colleague';
  profileUrl?: string;
};

export type ApplicationStatus = {
  stage: 'Discovery' | 'Triage' | 'Drafting' | 'Ready' | 'Applied' | 'Recruiter Screen' | 'Technical Round' | 'Portfolio Presentation' | '2nd Interview' | 'Final Round' | 'Offer' | 'Rejected' | 'Cancelled';
  supervisedRound?: boolean;      // Was this a supervised submission?
  receiptScreenshot?: string;     // Path to submission screenshot
  lastUpdated: string;
};

export type WorkExperience = {
  company: string;
  role: string;
  startDate: string;
  endDate: string;
  description: string;
  achievements: string[];
};

export type Education = {
  institution: string;
  degree: string;
  field: string;
  graduationYear: string;
};

export type SalaryExpectations = {
  currency: 'GBP' | 'USD' | 'EUR';
  minimumAcceptable: number;
  targetSalary: number;
  maximumAsk: number;
  negotiable: boolean;
};

// Reusable answers to common screening questions across applications
export type QuickAnswer = {
  id: string;
  question: string;         // The field label / question text
  answer: string;           // The stored answer
  usedCount: number;        // How many times this has been auto-applied
  lastUsed?: string;        // ISO date
};

export type UserProfile = {
  fullName: string;
  firstName?: string;
  lastName?: string;
  email: string;
  phone: string;
  location: string;
  portfolioUrl: string;
  portfolioPassword?: string;
  linkedInUrl?: string;
  resumeText: string;           // SOURCE OF TRUTH — never overwritten by AI
  experience: WorkExperience[];
  education: Education[];
  skills: string[];
  summary: string;
  targetTitles?: string[];
  alternativeTitles?: string[];
  targetLocations?: string[];
  /** The user's chosen anchor city for proximity-sorted searches (e.g. "Edgewater, FL") */
  baseLocation?: string;
  /** The subset of targetLocations currently selected for the next search run */
  activeSearchLocations?: string[];
  searchRadius?: number;
  matchStrictness?: 'exact' | 'strong' | 'flexible';
  booleanSearchString?: string;
  positioningSummary?: string;
  dailySearchEnabled?: boolean;
  // Application pipeline fields
  salaryExpectations?: SalaryExpectations;
  quickAnswers?: QuickAnswer[];   // Reusable answer bank for screening questions
  workAuthorisation?: string;     // e.g. "UK citizen", "Require sponsorship"
  noticePeriod?: string;          // e.g. "1 month", "Immediately available"
  applicationDailyLimit?: number; // Max applications per day (default: 15)
  supervisedModeCount?: number;   // How many supervised rounds before going autonomous
  dreamCompanies?: any[];
  nicheBoards?: any[];
  geminiApiKey?: string;
  preferredModel?: string;
};


// Mock data for initial UI
export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Product Designer',
    company: 'Experian',
    location: 'Nottingham (Hybrid)',
    description: 'Looking for a seasoned designer to lead our Fintech division...',
    score: 92,
    reason: 'Matches your 15+ years of experience and previous work in enterprise systems.',
    status: 'Discovery',
    url: 'https://linkedin.com/jobs/123',
    source: 'LinkedIn',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Staff UX Strategist',
    company: 'Boots',
    location: 'Nottingham (On-site)',
    description: 'Define the future of retail pharmacy UX...',
    score: 88,
    reason: 'Direct match for UX Strategy skills and local East Midlands presence.',
    status: 'Discovery',
    url: 'https://indeed.com/jobs/456',
    source: 'Indeed',
    createdAt: new Date().toISOString(),
  }
];
